import * as loginService from './login';
import * as userService from './user';
import * as menuService from './menu';
import * as ledgerService from './ledger';
import * as operationService from './operation';
export const login = loginService;
export const user = userService;
export const menu = menuService;
export const ledger = ledgerService;
export const operation = operationService;
